name: Automated GIF Responses

on:
  issue_comment:
    types:
      - created
  pull_request_review_comment:
    types:
      - created

jobs:
  gif-response:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Generate GIF Response
        run: |
          comment=$(jq -r '.comment.body' $GITHUB_EVENT_PATH)
          keywordsToGIFs=(
            ["hello"]="https://tenor.com/view/hello-gif-24408873"
            ["thank you"]="https://giphy.com/gifs/thanks-dayao-daydayao-G5MDBwmdTrVMpuRJix"
            ["excited"]="https://tenor.com/view/happy-excited-yes-yay-yas-gif-10395018"
            ["celebrate"]="https://tenor.com/search/gif-celebration-gifs"
            ["laugh"]="https://tenor.com/view/funny-laughing-lmao-that70s-show-giggle-gif-20649179"
            ["awesome"]="https://gifdb.com/gif/little-girl-awesome-thumbs-up-ip6w536ofbovbcdz.html"
          )
          gifURL=""
          for keyword in "${!keywordsToGIFs[@]}"; do
            if [[ $comment == *"$keyword"* ]]; then
              gifURL=${keywordsToGIFs[$keyword]}
              echo "Found keyword '$keyword' in comment. Posting GIF response..."
              curl -s -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -d "{\"body\": \"![GIF Response]($gifURL)\"}" \
                "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
              break
            fi
          done

          if [[ $gifURL == "" ]]; then
            echo "No relevant keyword found in comment. Skipping GIF response."
          fi
